server:
  port: 9501

eureka:
  register-with-eureka: false
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:admin@eureka1:7001/eureka,http://admin:admin@eureka2:7002/eureka,http://admin:admin@eureka3:7003/eureka

spring:
  application:
    name:  microcloud-zuul-gateway